version: '3.7'
services:
  backend-dev:
    image: yassinsiouda/computerjazzclub-back:dev
    build: backend/
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_migrations/:/pb_migrations
      - ./backend/pb_data/:/pb_data/
  frontend-dev:
    image: yassinsiouda/computerjazzclub-front:dev
    build: 
      context: ./front/
      target: "dev"
    volumes:
      - ./front/:/app/
    ports:
      - "3000:8080" #keep same port to avoid Cross scripting errors
    env_file:
      - .env