version: '3.7'
services:
  backend-dev:
    image: yassinsiouda/computerjazzclub-back:dev
    build: pocketbase/
    ports:
      - "${BACKEND_PORT}:8090"
    volumes:
      - ./backend/pb_migrations/:/pb_migrations
      - ./backend/pb_data/:/pb_data/
  frontend-dev:
    image: yassinsiouda/computerjazzclub-front:dev
    build: 
      context: front/
      target: "dev"
    volumes:
      - ./front/:/app/src
    ports:
      - "${FRONTEND_PORT}:3000" #keep same port to avoid Cross scripting errors
    env_file:
      - .env